show databases;
use dmddproject;
create table Dataset ( DatasetID INT Primary key, DatasetName Varchar(100), TypeOfDataset Varchar(100), NumberOfColumns INT, NumberOfRecords INT);
insert into Dataset (DatasetID,DatasetName,TypeOfDataset,NumberOfColumns,NumberOfRecords) values(1,'Diabetes_train','csv',50,50001);
alter table datadescription add constraint Primary key (ID) ;
alter table datadescription add constraint Foreign key (DatasetID) references Dataset(DatasetID);	
select * from datadescription;
select * from Metadatatable;
alter table Metadatatable add constraint Primary key (Runtime_ID) ;
alter table Metadatatable add constraint Foreign key (DatasetID) references Dataset(DatasetID);	
select * from modeltable;
alter table modeltable modify column ModelName VARCHAR(512) ;
alter table modeltable add constraint primary key (ModelName); 
alter table modeltable add constraint foreign key (Runtime_ID) references Metadatatable(Runtime_ID);
select * from HPDRFtable;
alter table HPDRFtable add constraint primary key (HP_ID); 
alter table HPDRFtable modify column ModelName VARCHAR(512);
alter table HPDRFtable add constraint foreign key (ModelName) references modeltable(ModelName);
select * from HPGBMtable;
alter table HPGBMtable add constraint primary key (HP_ID); 
alter table HPGBMtable modify column ModelName VARCHAR(512);
alter table HPGBMtable add constraint foreign key (ModelName) references modeltable(ModelName);
select * from HPGLMtable;
alter table HPGLMtable add constraint primary key (HP_ID); 
alter table HPGLMtable modify column ModelName VARCHAR(512);
alter table HPGLMtable add constraint foreign key (ModelName) references modeltable(ModelName);
select * from metrictable;
alter table metrictable add constraint primary key (Metric_ID); 
alter table metrictable modify column ModelName VARCHAR(512);
alter table metrictable add constraint foreign key (ModelName) references modeltable(ModelName);

